### ISSUE TITLE
Sample app is missing babel-polyfill dependency

### ISSUE THREAD

**Issue by martinvol** [opentok/accelerator-core-js#17]
### General information

- Library version(s):
- iOS/Android/Browser version(s): Chrome 
- Devices/Simulators/Machine affected: Linux
- Reproducible in the demo project? (Yes/No):  Yes (this is an issue of the demo project)
- Related issues: -

#### Expected behavior

Sample react app to run.

#### Actual behavior

Crash displayed on console and browser.

#### Steps to reproduce

Instructions here: https://github.com/opentok/accelerator-core-js/blob/master/react-sample-app/README.md

#### Crash log? Screenshots? Videos? Sample project?

Failed to compile.

The browser also displays the same error

```
Error in ./src/ot-core/core.js
Module not found: 'babel-polyfill' in /home/martin/Dropbox/current/accelerator-core-js/react-sample-app/src/ot-core

 @ ./src/ot-core/core.js 15:0-25

```

## Question or Feature Request

Need to add "babel-polyfill" to dependence list. Running `npm install babel-polyfill` solved the issue.

**Comment by adrice727** [comment]
Thanks @martinvol.  Closed with https://github.com/opentok/accelerator-core-js/pull/18.
