### ISSUE TITLE
Bad sdkWrapper link on README.md

### ISSUE THREAD

**Issue by kascote** [opentok/accelerator-core-js#57]
## New issue checklist

- [x] I have read all of the [`README`](../README.md) 
- [x] I have searched [existing issues](https://github.com/opentok/accelerator-core-js/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 2.0.12
- iOS/Android/Browser version(s): 
- Devices/Simulators/Machine affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

## Bug report

The link to the sdkWrapper doc is wrong on the README.md file

#### Expected behavior

show the doc

#### Actual behavior

nothing

#### Steps to reproduce

clink the link

#### Crash log? Screenshots? Videos? Sample project?

>...

## Question or Feature Request

> ...

**Comment by maikthomas** [comment]
deploy delayed by #61 
will deploy manually if not fixed.

**Comment by maikthomas** [comment]
PR accepted, thanks.
