### ISSUE TITLE
mismatch enableSubscriberAudio and enableSubscriberVideo on sdkWrapper

### ISSUE THREAD

**Issue by kascote** [opentok/accelerator-core-js#59]
## New issue checklist

- [x] I have read all of the [`README`](../README.md) 
- [x] I have searched [existing issues](https://github.com/opentok/accelerator-core-js/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 2.0.12
- iOS/Android/Browser version(s): Browser
- Devices/Simulators/Machine affected: all
- Reproducible in the demo project? (Yes/No): no
- Related issues:

## Bug report

the enableSubscriberAudio/enableSubscriberVideo methods on sdkWrapper mismatch the call to the same method on the subscriber

https://github.com/opentok/accelerator-core-js/blob/master/src/sdk-wrapper/sdkWrapper.js#L183
https://github.com/opentok/accelerator-core-js/blob/master/src/sdk-wrapper/sdkWrapper.js#L195

#### Expected behavior

call the correct methods

#### Actual behavior

Video call Audio and vice versa

#### Steps to reproduce

use the methods on the sdkWrapper

#### Crash log? Screenshots? Videos? Sample project?

>...

## Question or Feature Request

> ...

**Comment by maikthomas** [comment]
deploy delayed by #61
will deploy manually if not fixed.

**Comment by maikthomas** [comment]
Fix deployed in https://github.com/opentok/accelerator-core-js/tree/v2.0.13 now in npm
