### ISSUE TITLE
Chrome Extension issue

### ISSUE THREAD

**Issue by Jagdeep-Sing** [opentok/accelerator-core-js#67]
Chrome Extension created & Added from webStore, but always when start Screen share it shows install extension ,if i click accept it installs again but screen share not started

**Comment by Jagdeep-Sing** [comment]
WHy no one reply here???????

**Comment by maikthomas** [comment]
@Jagdeep-Sing we are looking into your issue and will reply when we have some information.
Thanks,
Mike

**Comment by Jagdeep-Sing** [comment]
Thanks Mike, I followed all the steps:
1. enter my url in manifest.json of extension under matches
2.verify my URL in google console
3.placed extensionID in App.js file under extensionID variable

I'm waiting for your reply..

**Comment by maikthomas** [comment]
@Jagdeep-Sing 

I see from [stackoverflow](https://stackoverflow.com/questions/48220824/unable-to-start-screenshare-on-opentok-using-opentok-accelerator-core-js-on-chro) that you are using the [vanilla js sample app](https://github.com/opentok/accelerator-sample-apps-js/tree/master/vanilla-js-sample-app).

I have tried this app locally and was able to set up screen sharing using the extension build from here: https://github.com/opentok/screensharing-extensions/tree/master/chrome/ScreenSharing

I was able to run this on localhost and on an external url (using ngrok to set up a tunnel to my localhost).
The matches in my `manifest.json` look like this:
```
    "matches": [
      "https://<my-ngrok-subdomain>.ngrok.io/*",
      "http://localhost:8080/*"
    ]
```

However, when my matches weren't correct it showed the installation dialog.

I recommend you copy that sharing extension, [load it into chrome to test locally ](https://github.com/opentok/screensharing-extensions/tree/master/chrome/ScreenSharing#testing-your-unpacked-extension) and confirm that you have the matches and everything else working before publishing to the Chrome Web Store.

Thanks,
Mike

**Comment by Jagdeep-Sing** [comment]
Oh, Thanks Mike.

You saved my Days..

The error was in my URL. I'm not adding `*` behind URL.
When added by seeing your example, it worked like magic.
was stucked on it from las week.
Thanks a lot again Mike :+1:

**Comment by maikthomas** [comment]
Great! You're welcome, I'm glad you sorted it!
