### ISSUE TITLE
Auto-subscribe works unreliably in group chats

### ISSUE THREAD

**Issue by timkishkin** [opentok/accelerator-core-js#68]
### General information

- Library version(s): 2.0.14
- iOS/Android/Browser version(s): Google Chrome 67.0.3396.99
- Devices/Simulators/Machine affected: Web browser
- Reproducible in the demo project? (Yes/No): ? (I had trouble running it)

## Bug report

Auto-subscribe works unreliably in group chats. It results in some people not seeing each other in certain cases.

Apparently the problem is in communication.js. It happens during *startCall()* method processing, when *subscribeToInitialStreams()* method is already running, but *active* flag is still false, and in such moment a new remote stream is created (*streamCreated* event). *subscribe()* is not called as *active* is still false, but *subscribeToInitialStreams()* also ignores this new stream as enumeration of streams was already started and it didn't include the new stream.

#### Expected behavior

Create a group video call with 4 members. All members should join approximately at the same time.
"subscribeToCamera" event should be fired for each remote stream (3 times). On each client, otCore.state().subscribers must contain 3 streams.

#### Actual behavior

In some cases, "subscribeToCamera" event is fired less than 3 times. otCore.state().subscribers contains less than 3 streams.

#### Steps to reproduce

Create a group video call with 4 members. All members should join approximately at the same time.

**Comment by timkishkin** [comment]
I've prepared a PR: https://github.com/opentok/accelerator-core-js/pull/69

**Comment by timkishkin** [comment]
In my fix, I switch the communication module state to *active* immediately after *startCall()* is called, so new streams will always be subscribed to when they appear. In order to avoid double-subscribing to such streams when *subscribeToInitialStreams()* is called, I've made a modification to only consider old streams (which existed before *startCall()*) when subscribing to initial streams.

**Comment by maikthomas** [comment]
Thanks for your fix @timkishkin ! 
It has been deployed in npm version 2.0.15
