### ISSUE TITLE
Bad link to the Reac sample app in the README.md

### ISSUE THREAD

**Issue by skokovskyi** [opentok/accelerator-core-js#82]
## New issue checklist

- [x] I have read all of the [`README`](../README.md) 
- [x] I have searched [existing issues](https://github.com/opentok/accelerator-core-js/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

#### Expected behavior
Should be https://github.com/opentok/accelerator-sample-apps-js/tree/master/react-sample-app

#### Actual behavior
Link to https://github.com/opentok/accelerator-core-js/tree/master/react-sample-app

#### Crash log? Screenshots? Videos? Sample project?
<img width="1038" alt="Знімок екрана 2020-06-17 о 13 09 07" src="https://user-images.githubusercontent.com/53641000/84885660-02685480-b09c-11ea-9018-4e07b3593fa5.png">

**Comment by MichaelJolley** [comment]
Thanks for catching that @skokovskyi! I've got a PR submitted to update it.
