### ISSUE TITLE
Vide Chat Embeds - stylesheet not loading

### ISSUE THREAD

**Issue by abdulmoizlakhani** [opentok/accelerator-core-js#93]
Hi,

I am using video chat embed and according to documentation, I'm using the following code.

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <div id="otEmbedContainer" style="width:800px; height:640px"></div>
    <script
        src="https://tokbox.com/embed/embed/ot-embed.js?embedId=<embed-id>&room=DEFAULT_ROOM"></script>
</body>

</html>
```

It's working fine but the stylesheet is not loading and I'm unable to see a small screen when video chat starts at the top right.

I am getting the following error:
`OpenTok:StylableComponent:warn Calling setStyle() has no effect because theshowControls option was set to false +0ms`
`OpenTok:processPubOptions:warn OT.Publisher: Setting video constraint to false, there are no video sources +0ms`
`OpenTok:StylableComponent:warn Calling setStyle() has no effect because theshowControls option was set to false +14s`

![image](https://user-images.githubusercontent.com/25384728/96386111-e2fc4800-11b1-11eb-936d-be3d72143b84.png)

The screen is showing like below:
![image](https://user-images.githubusercontent.com/25384728/96386080-9add2580-11b1-11eb-9ee0-b726e6bf8df7.png)

Please share your feedback.

Thanks

**Comment by MichaelJolley** [comment]
Hi @abdulmoizlakhani, embeds aren't covered by this repo. It is for our JS accelerators. I'd suggest reviewing https://support.tokbox.com/ for support options.  Thanks!
