### ISSUE TITLE
Stale camera subscriber DOM elements are not unmounted

### ISSUE THREAD

**Issue by doronrk** [opentok/accelerator-core-js#97]
## New issue checklist

- [x] I have read all of the [`README`](../README.md) 
- [x] I have searched [existing issues](https://github.com/opentok/accelerator-core-js/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): "opentok-accelerator-core": "^2.0.17",
- iOS/Android/Browser version(s): Chrome Version 87.0.4280.88  
- Devices/Simulators/Machine affected:
- Reproducible in the demo project? (Yes/No): Sporadically reproducable
- Related issues:

#### Expected behavior

>  camera subscriber DOM elements should be unmounted when their corresponding streams are destroyed.

#### Actual behavior

> I’m noticing that 2 out of 3 stale camera subscriber DOM elements are stale, i.e. still mounted when a valid stream only exists for one of the three.

#### Steps to reproduce

> Seems to happen sporadically in my prototype 

#### Crash log? Screenshots? Videos? Sample project?

> 
![image](https://user-images.githubusercontent.com/4276179/103397098-9dca8f80-4aeb-11eb-9700-e05ff0b8c31c.png)
![image](https://user-images.githubusercontent.com/4276179/103397103-a15e1680-4aeb-11eb-9323-2b099acefc01.png)
![image](https://user-images.githubusercontent.com/4276179/103397110-a58a3400-4aeb-11eb-92cf-1fb6f130a428.png)

## Question or Feature Request

> Could this issue be caused by a bug in my application code? My understanding is that the accelerator-core is responsible for handling DOM updates behind the scenes.

**Comment by doronrk** [comment]
Update, this bug is correlated with getting N back-to-back stream created events for each of the N duplicate DOM elements.

![image](https://user-images.githubusercontent.com/4276179/103492440-b256a280-4ddf-11eb-9892-5b50344c0ece.png)

**Comment by doronrk** [comment]
I resolved it. It turns out my issue was the same as the one described here:

https://github.com/opentok/opentok-react-native/issues/271

Disconnecting and unregistering all event handlers in my useEffect cleanup did the trick.

**Comment by Alan-Billi** [comment]
Hey @doronrk , can you give me more details on how you've unregistered / disconnected those events ?
I have the same issue in my app and can't find which method I should call for that.

Thanks !
